# Generated by Django 4.1.5 on 2023-01-30 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('room', models.CharField(help_text='Enter the room in which the sensor sits', max_length=20)),
                ('description', models.CharField(blank=True, help_text='Enter, if necessary, additional information about the sensor', max_length=200)),
                ('measurements', models.ManyToManyField(to='sensordata.measure')),
            ],
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.sensor')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensordata.measure')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
