# Generated by Django 4.1.5 on 2023-01-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Measure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(help_text='Enter the room in which the sensor sits', max_length=20)),
                ('description', models.CharField(help_text='Enter, if necessary, additional information about the sensor', max_length=200)),
                ('measurements', models.ManyToManyField(to='sensordata.measure')),
            ],
        ),
    ]
