# Generated by Django 4.1.5 on 2023-01-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
