# Generated by Django 4.1.5 on 2023-01-30 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0002_alter_measure_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='description',
            field=models.CharField(help_text='Enter, if necessary, additional information about the sensor', max_length=200),
        ),
    ]
