# Generated by Django 4.1.5 on 2023-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0002_measurement'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='name',
            field=models.CharField(default='a', max_length=20),
            preserve_default=False,
        ),
    ]
