# Generated by Django 4.1.5 on 2023-01-30 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_alter_sensor_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-sensor', '-unit', '-time']},
        ),
    ]
