# Generated by Django 4.1.5 on 2023-01-29 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sensordata', '0003_measure_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['-time']},
        ),
    ]
